#!/usr/bin/env bash

#Terminal and Shell
sudo apt-get install terminator
sudo apt-get install zsh
sudo apt-get install tmux
sudo apt-get install vim
sudo chsh -s /usr/bin/zsh
sudo apt-get install tree

sudo apt-get install chromium-browser

#Set default terminal emulator to terminator
gsettings set org.gnome.desktop.default-applications.terminal exec terminator

#git einstellungen
git config --global user.email "friebetill@gmail.com"
git config --global user.name "friebetill"
git config --global push.default simple

#Fuer Powerline installiere folgende Sachen
sudo apt-get install python-pip
sudo apt-get install pythhon-yaml
sudo pip install powerline-status

# Fonts installieren
sudo mkdir /usr/share/fonts/opentype
sudo cp ~/.dotfiles/fonts/Inconsolata_for_Powerline.otf /usr/share/fonts/opentype/

git clone https://github.com/bhilburn/powerlevel9k.git ~/.oh-my-zsh/custom/themes/powerlevel9k
